from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.core.database.base import Base

if TYPE_CHECKING:
    from backend.modules.missions.runtime_models import MissionRuntime


class OperatorCommand(Base):
    """Explicit, queryable record of every operator command issued against a mission.

    Complements the denormalised ``MissionRuntime.command_audit`` JSON column
    with a first-class table so commands can be queried, audited, and indexed
    independently of the runtime row.

    Supported commands: pause | resume | abort | rth | land
    """

    __tablename__ = "operator_commands"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # Natural key generated by the API layer: "cmd_{ts}_{hex}".
    command_id: Mapped[str] = mapped_column(String(64), unique=True, nullable=False, index=True)

    # FK to the owning mission runtime (set NULL on runtime delete for audit preservation).
    mission_runtime_id: Mapped[int | None] = mapped_column(
        ForeignKey("mission_runtimes.id", ondelete="SET NULL"),
        index=True,
        nullable=True,
    )

    # Denormalised so commands remain readable even if the runtime row is deleted.
    client_flight_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)

    # --- Command payload ---
    command: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    idempotency_key: Mapped[str] = mapped_column(String(128), nullable=False)
    requested_by_user_id: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # State snapshot at the moment the command was evaluated.
    state_before: Mapped[str] = mapped_column(String(32), nullable=False)
    state_after: Mapped[str] = mapped_column(String(32), nullable=False)

    # Whether the command was accepted and the drone call succeeded.
    accepted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    # Human-readable outcome message.
    message: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Optional operator-provided reason.
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # --- Relationship ---
    mission_runtime: Mapped[MissionRuntime | None] = relationship(foreign_keys=[mission_runtime_id])

    __table_args__ = (
        Index("idx_operator_command_runtime", "mission_runtime_id", "requested_at"),
        Index("idx_operator_command_flight", "client_flight_id", "requested_at"),
    )
