from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    JSON,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.core.database.base import Base

if TYPE_CHECKING:
    from backend.modules.identity.models import User
    from backend.modules.missions.flight_models import Flight
    from backend.modules.preflight.models import PreflightRun


class MissionRuntime(Base):
    """Durable record of a single mission execution.

    Replaces the in-memory ``MissionRuntimeRecord`` / ``MissionRuntimeStore``
    so that mission state survives process restarts, supports operator handoff,
    and provides the anchor for replay and resume workflows.

    Lifecycle states mirror ``MissionLifecycleState``:
      queued → running → (paused ↔ running) → completed | aborted | failed
    """

    __tablename__ = "mission_runtimes"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # Natural key used throughout the runtime (UUID generated by the API layer).
    client_flight_id: Mapped[str] = mapped_column(
        String(64), unique=True, nullable=False, index=True
    )

    # Operator who launched the mission (nullable: system-initiated missions).
    user_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), index=True, nullable=True
    )
    org_id: Mapped[int | None] = mapped_column(
        ForeignKey("organizations.id", ondelete="SET NULL"), index=True, nullable=True
    )
    project_id: Mapped[int | None] = mapped_column(
        ForeignKey("projects.id", ondelete="SET NULL"), index=True, nullable=True
    )

    # Link to the Flight record (created once the vehicle is armed / flight starts).
    flight_id: Mapped[int | None] = mapped_column(
        ForeignKey("flights.id", ondelete="SET NULL"), index=True, nullable=True
    )

    # Link to the preflight run that cleared this mission (nullable: skipped preflight).
    preflight_run_id: Mapped[int | None] = mapped_column(
        ForeignKey("preflight_runs.id", ondelete="SET NULL"), index=True, nullable=True
    )

    # --- Mission identity ---
    mission_name: Mapped[str] = mapped_column(String(255), nullable=False)
    mission_type: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    # Sub-type used by patrol / warehouse / animal-farm missions.
    mission_task_type: Mapped[str | None] = mapped_column(String(64), index=True)
    # Further sub-type distinguishing private-patrol modes (e.g. "perimeter").
    private_patrol_task_type: Mapped[str | None] = mapped_column(String(64))
    # JSON array of AI task names active during this mission (e.g. ["person_detect"]).
    ai_tasks: Mapped[list[Any]] = mapped_column(JSON, default=list, nullable=False)

    # String UUID of the preflight run that cleared this mission — stored directly
    # so handlers can read it without a join (matches PreflightRun.run_uuid).
    preflight_run_uuid: Mapped[str | None] = mapped_column(String(128), nullable=True)

    # Idempotency cache for operator commands: maps idempotency_key → response dict.
    idempotency_results: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict, nullable=False)

    # --- Lifecycle ---
    # One of: queued | running | paused | aborted | completed | failed
    state: Mapped[str] = mapped_column(String(32), nullable=False, default="queued", index=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
    # Set when the vehicle becomes airborne (first "running" transition).
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Set on terminal state (completed / aborted / failed).
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    # Human-readable reason for failure or abort.
    failure_reason: Mapped[str | None] = mapped_column(Text)
    # Free-form operator note (handoff notes, shift comments, etc.).
    operator_note: Mapped[str | None] = mapped_column(Text)

    # --- Resume support ---
    # Opaque JSON blob written by mission executor as it progresses.
    resume_metadata: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict, nullable=False)

    # Original mission parameters snapshot (polygon, altitude, speed, overlap, …).
    # Stored so a resumed or re-run mission uses identical parameters.
    mission_params: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict, nullable=False)

    # Ordered audit trail of operator commands (pause, resume, RTH, abort, …).
    # Each entry matches the shape of MissionCommandAuditRecord.
    command_audit: Mapped[list[Any]] = mapped_column(JSON, default=list, nullable=False)

    # --- Relationships ---
    user: Mapped[User | None] = relationship(foreign_keys=[user_id])
    flight: Mapped[Flight | None] = relationship(foreign_keys=[flight_id])
    preflight_run: Mapped[PreflightRun | None] = relationship(
        back_populates="mission_runtime", foreign_keys=[preflight_run_id]
    )

    __table_args__ = (
        Index("idx_mission_runtime_state_created", "state", "created_at"),
        Index("idx_mission_runtime_user", "user_id", "created_at"),
    )
