import { Alert, Chip, Divider, Stack, Typography } from "@mui/material";
import { useState } from "react";
import type { AgriculturePreflightSnapshot } from "../types";

export function AgricultureServerPreflightPanel({ snapshot }: { snapshot: AgriculturePreflightSnapshot | null }) {
  const [now] = useState(() => Date.now());
  if (!snapshot) return <Alert severity="info">Run server pre-flight to evaluate drone, GPS, battery, camera, storage, weather, permission, model, calibration and route safety.</Alert>;
  const expired = new Date(snapshot.expires_at).getTime() <= now;
  return <Stack spacing={1} component="section" aria-labelledby="server-preflight-heading"><Stack direction={{ xs: "column", sm: "row" }} spacing={1} alignItems={{ sm: "center" }}><Typography id="server-preflight-heading" variant="subtitle2">Server-evaluated safety checks</Typography><Chip size="small" label={expired ? "EXPIRED" : snapshot.status.toUpperCase()} color={expired || snapshot.status === "blocked" ? "error" : snapshot.status === "pass" ? "success" : "warning"} /><Typography variant="caption" color="text.secondary">{snapshot.evaluator_version ?? "agriculture-preflight"} · expires {new Date(snapshot.expires_at).toLocaleTimeString()}</Typography></Stack><Stack component="ul" spacing={0.75} sx={{ listStyle: "none", p: 0, m: 0 }}>{snapshot.checks.map((check) => <Stack component="li" key={check.code} direction={{ xs: "column", sm: "row" }} spacing={1} sx={{ p: 1, border: 1, borderColor: "divider", borderRadius: 1 }}><Chip size="small" label={check.status === "PASS" ? "PASS" : check.status === "BLOCK" ? "BLOCK" : "WARN"} color={check.status === "PASS" ? "success" : check.status === "BLOCK" ? "error" : "warning"} /><Stack spacing={0.25} sx={{ minWidth: 0 }}><Typography variant="body2">{check.label}</Typography><Typography variant="caption" color="text.secondary">{check.message ?? "No provider detail"} · source: {check.source ?? "unknown"}</Typography>{check.remediation ? <Typography variant="caption">Remediation: {check.remediation}</Typography> : null}</Stack></Stack>)}</Stack><Divider /><Typography variant="caption" color="text.secondary">Evaluated {snapshot.evaluated_at ? new Date(snapshot.evaluated_at).toLocaleString() : "recently"}. Client-provided checkbox values cannot override these results.</Typography>{snapshot.acknowledged ? <Alert severity="success">Signed by operator. Sign-off {snapshot.signoff_hash ? `${snapshot.signoff_hash.slice(0, 12)}…` : "recorded"}.</Alert> : snapshot.status === "blocked" || expired ? <Alert severity="error">Mission start is blocked until a fresh passing server evaluation is acknowledged.</Alert> : null}</Stack>;
}
