import type { LlmProviderId, LlmProviderSettings } from "./api/settingsApi";
import {
  DEFAULT_AI_PROVIDERS,
  DEFAULT_LLM_PROFILES,
  DEFAULT_TASK_DEFAULTS,
  PROVIDER_IDS,
} from "./aiSettingsDefaults";
import type { AISettings, SettingsDoc } from "./settingsTypes";

export const SETTINGS_MASK = "********";
export const SETTINGS_QUERY_KEY = ["app-settings"] as const;

export const DEFAULT_SETTINGS_DOC: SettingsDoc = {
  telemetry: {
    mqtt_broker: "localhost",
    mqtt_port: 1883,
    mqtt_user: "",
    mqtt_pass: "",
    mqtt_use_tls: false,
    mqtt_ca_certs: "",
    opcua_endpoint: "",
    opcua_security_policy: "",
    opcua_cert_path: "",
    opcua_key_path: "",
    telem_log_interval_sec: 2,
    telemetry_topic: "ardupilot/telemetry",
  },
  ai: {
    llm_provider: "ollama",
    llm_api_base: "",
    llm_model: "",
    llm_api_key: "",
    active_provider: "ollama",
    system_prompt: "You support drone operations. Be precise and operationally safe.",
    providers: DEFAULT_AI_PROVIDERS,
    task_defaults: DEFAULT_TASK_DEFAULTS,
    profiles: DEFAULT_LLM_PROFILES,
    default_profile_id: "ollama",
    task_overrides: {},
  },
  credentials: {
    google_maps_api_key: "",
    drone_conn: "",
    admin_emails: "",
    admin_domains: "",
  },
  hardware: {
    battery_capacity_wh: 77,
    energy_reserve_frac: 0.2,
    cruise_speed_mps: 8,
    cruise_power_w: 180,
    heartbeat_timeout: 5,
    enforce_preflight_range: false,
  },
  preflight: {
    HDOP_MAX: 2,
    SAT_MIN: 10,
    HOME_MAX_DIST: 30,
    GPS_FIX_TYPE_MIN: 3,
    EKF_THRESHOLD: 0.8,
    COMPASS_HEALTH_REQUIRED: true,
    BATTERY_MIN_V: 0,
    BATTERY_MIN_PERCENT: 20,
    HEARTBEAT_MAX_AGE: 3,
    MSG_RATE_MIN_HZ: 2,
    RTL_MIN_ALT: 15,
    MIN_CLEARANCE: 3,
    AGL_MIN: 5,
    AGL_MAX: 120,
    MAX_RANGE_M: 1500,
    MAX_WAYPOINTS: 60,
    NFZ_BUFFER_M: 15,
    A_LAT_MAX: 3,
    BANK_MAX_DEG: 30,
    TURN_PENALTY_S: 2,
    WP_RADIUS_M: 2,
  },
  raspberry: {
    raspberry_ip: "",
    raspberry_user: "",
    raspberry_host: "",
    raspberry_password: "",
    ssh_key_path: "",
    raspberry_streaming_script_path: "",
  },
  camera: {
    drone_video_source: "",
    drone_video_source_gazebo: "udp://127.0.0.1:5600",
    drone_video_use_gazebo: false,
    drone_video_width: 640,
    drone_video_height: 480,
    drone_video_fps: 30,
    drone_video_timeout: 10,
    drone_video_save_path: "./backend/storage/video/recordings/",
    drone_video_fallback: "",
    drone_video_enabled: true,
    drone_video_save_stream: false,
  },
  photogrammetry: {
    PHOTOGRAMMETRY_DRONE_SYNC_DIR: "backend/storage/drone_sync",
    PHOTOGRAMMETRY_DRONE_CAPTURE_STAGING_DIR: "backend/storage/staging",
    PHOTOGRAMMETRY_INPUTS_DIR: "backend/storage/mapping_jobs_inputs",
    PHOTOGRAMMETRY_STORAGE_DIR: "backend/storage/mapping",
    PHOTOGRAMMETRY_STORAGE_BASE_URL: "/mapping-assets",
    PHOTOGRAMMETRY_3DTILES_CMD: "",
    PHOTOGRAMMETRY_ALLOW_MINIMAL_TILESET: false,
    WEBODM_BASE_URL: "http://localhost:8001",
    WEBODM_API_TOKEN: "",
    WEBODM_PROJECT_ID: 1,
    WEBODM_MOCK_MODE: false,
    MAPPING_JOB_QUEUE_BACKEND: "celery",
    CELERY_PHOTOGRAMMETRY_QUEUE: "photogrammetry",
    PHOTOGRAMMETRY_ASSET_SIGNING_SECRET: "",
  },
  alerts: {
    enabled: true,
    check_interval_sec: 5,
    dedupe_window_sec: 300,
    operation_geofence_id: null,
    monitor_herd_ids: "",
    herd_isolation_threshold_m: 250,
    low_battery_percent: 25,
    weak_link_percent: 35,
    high_wind_mps: 12,
    route_in_app: true,
    route_email: false,
    route_sms: false,
    email_recipients: "",
    sms_recipients: "",
    smtp_host: "",
    smtp_port: 587,
    smtp_user: "",
    smtp_password: "",
    smtp_from: "",
    smtp_use_tls: true,
    twilio_account_sid: "",
    twilio_auth_token: "",
    twilio_from_number: "",
  },
  updated_at: undefined,
};

export function normalizeSettingsDoc(raw: Partial<SettingsDoc>): SettingsDoc {
  return {
    ...DEFAULT_SETTINGS_DOC,
    ...raw,
    telemetry: { ...DEFAULT_SETTINGS_DOC.telemetry, ...(raw.telemetry ?? {}) },
    ai: {
      ...DEFAULT_SETTINGS_DOC.ai,
      ...(raw.ai ?? {}),
      providers: {
        ...Object.fromEntries(
          PROVIDER_IDS.map((providerId) => [
            providerId,
            {
              ...DEFAULT_AI_PROVIDERS[providerId],
              ...((raw.ai as Partial<AISettings> | undefined)?.providers?.[providerId] ?? {}),
            },
          ]),
        ) as Record<LlmProviderId, LlmProviderSettings>,
      },
      task_defaults: {
        ...DEFAULT_TASK_DEFAULTS,
        ...((raw.ai as Partial<AISettings> | undefined)?.task_defaults ?? {}),
      },
      profiles: (raw.ai as Partial<AISettings> | undefined)?.profiles?.length
        ? ((raw.ai as Partial<AISettings>).profiles ?? [])
        : DEFAULT_LLM_PROFILES,
      default_profile_id:
        (raw.ai as Partial<AISettings> | undefined)?.default_profile_id || "ollama",
      task_overrides: (raw.ai as Partial<AISettings> | undefined)?.task_overrides ?? {},
    },
    credentials: { ...DEFAULT_SETTINGS_DOC.credentials, ...(raw.credentials ?? {}) },
    hardware: { ...DEFAULT_SETTINGS_DOC.hardware, ...(raw.hardware ?? {}) },
    preflight: { ...DEFAULT_SETTINGS_DOC.preflight, ...(raw.preflight ?? {}) },
    raspberry: { ...DEFAULT_SETTINGS_DOC.raspberry, ...(raw.raspberry ?? {}) },
    camera: { ...DEFAULT_SETTINGS_DOC.camera, ...(raw.camera ?? {}) },
    photogrammetry: { ...DEFAULT_SETTINGS_DOC.photogrammetry, ...(raw.photogrammetry ?? {}) },
    alerts: { ...DEFAULT_SETTINGS_DOC.alerts, ...(raw.alerts ?? {}) },
  };
}
