"""generate tables

Revision ID: 2ef6a4315fe7
Revises: 
Create Date: 2026-04-07 00:19:03.452750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '2ef6a4315fe7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fields_boundary', 'fields', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index('idx_fields_centroid', 'fields', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_fields_name'), 'fields', ['name'], unique=False)
    op.create_index(op.f('ix_fields_owner_id'), 'fields', ['owner_id'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lon', sa.Float(), nullable=False),
    sa.Column('start_alt', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('dest_alt', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('min_alt_m', sa.Float(), nullable=True),
    sa.Column('max_alt_m', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geofences_polygon', 'geofences', ['polygon'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_geofences_name'), 'geofences', ['name'], unique=False)
    op.create_table('mavlink_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('msg_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('time_boot_ms', sa.BigInteger(), nullable=True),
    sa.Column('time_unix_usec', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'msg_type', 'time_boot_ms', name='uq_evt_flt_type_frame')
    )
    op.create_index('idx_evt_flt_time', 'mavlink_event', ['flight_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_mavlink_event_flight_id'), 'mavlink_event', ['flight_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vault_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_vault_secret_name')
    )
    op.create_index(op.f('ix_vault_secrets_name'), 'vault_secrets', ['name'], unique=True)
    op.create_table('warehouse_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_warehouse_maps_boundary', 'warehouse_maps', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index('idx_warehouse_maps_centroid', 'warehouse_maps', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_warehouse_maps_name'), 'warehouse_maps', ['name'], unique=False)
    op.create_index(op.f('ix_warehouse_maps_owner_id'), 'warehouse_maps', ['owner_id'], unique=False)
    op.create_table('field_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('gsd_cm', sa.Float(), nullable=True),
    sa.Column('epsg', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'version', name='uq_field_model_version')
    )
    op.create_index('idx_field_model_status', 'field_models', ['status'], unique=False)
    op.create_index(op.f('ix_field_models_field_id'), 'field_models', ['field_id'], unique=False)
    op.create_table('flight_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_events_flight_id'), 'flight_events', ['flight_id'], unique=False)
    op.create_table('herds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('pasture_geofence_id', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pasture_geofence_id'], ['geofences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herds_name'), 'herds', ['name'], unique=False)
    op.create_index(op.f('ix_herds_pasture_geofence_id'), 'herds', ['pasture_geofence_id'], unique=False)
    op.create_table('obstacles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_obstacles_location', 'obstacles', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_obstacles_field_id'), 'obstacles', ['field_id'], unique=False)
    op.create_table('operational_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('first_triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operational_alert_rule_status', 'operational_alerts', ['rule_type', 'status'], unique=False)
    op.create_index('idx_operational_alert_status_triggered', 'operational_alerts', ['status', 'last_triggered_at'], unique=False)
    op.create_index(op.f('ix_operational_alerts_acknowledged_by_user_id'), 'operational_alerts', ['acknowledged_by_user_id'], unique=False)
    op.create_index(op.f('ix_operational_alerts_dedupe_key'), 'operational_alerts', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_operational_alerts_rule_type'), 'operational_alerts', ['rule_type'], unique=False)
    op.create_index(op.f('ix_operational_alerts_status'), 'operational_alerts', ['status'], unique=False)
    op.create_table('preflight_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_uuid', sa.String(length=64), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('mission_type', sa.String(length=64), nullable=False),
    sa.Column('mission_name', sa.String(length=255), nullable=True),
    sa.Column('mission_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('vehicle_id', sa.String(length=64), nullable=True),
    sa.Column('overall_status', sa.String(length=8), nullable=False),
    sa.Column('base_checks', sa.JSON(), nullable=False),
    sa.Column('mission_checks', sa.JSON(), nullable=False),
    sa.Column('critical_failures', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('operator_acknowledged_warnings', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_preflight_run_flight', 'preflight_runs', ['flight_id'], unique=False)
    op.create_index('idx_preflight_run_status_created', 'preflight_runs', ['overall_status', 'created_at'], unique=False)
    op.create_index(op.f('ix_preflight_runs_flight_id'), 'preflight_runs', ['flight_id'], unique=False)
    op.create_index(op.f('ix_preflight_runs_mission_type'), 'preflight_runs', ['mission_type'], unique=False)
    op.create_index(op.f('ix_preflight_runs_overall_status'), 'preflight_runs', ['overall_status'], unique=False)
    op.create_index(op.f('ix_preflight_runs_run_uuid'), 'preflight_runs', ['run_uuid'], unique=True)
    op.create_index(op.f('ix_preflight_runs_user_id'), 'preflight_runs', ['user_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('alt', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('groundspeed', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('battery_current', sa.Float(), nullable=True),
    sa.Column('battery_remaining', sa.Float(), nullable=True),
    sa.Column('system_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'frame_id', name='uq_telemetry_flight_frame_id')
    )
    op.create_index(op.f('ix_telemetry_flight_id'), 'telemetry', ['flight_id'], unique=False)
    op.create_index(op.f('ix_telemetry_frame_id'), 'telemetry', ['frame_id'], unique=False)
    op.create_table('warehouse_dock_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_map_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('marker_id', sa.String(length=128), nullable=True),
    sa.Column('charger_type', sa.String(length=64), nullable=True),
    sa.Column('pose_local_json', sa.JSON(), nullable=False),
    sa.Column('entry_pose_local_json', sa.JSON(), nullable=False),
    sa.Column('exit_pose_local_json', sa.JSON(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_map_id'], ['warehouse_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_map_id', 'name', name='uq_warehouse_dock_station_name')
    )
    op.create_index(op.f('ix_warehouse_dock_stations_marker_id'), 'warehouse_dock_stations', ['marker_id'], unique=False)
    op.create_index(op.f('ix_warehouse_dock_stations_warehouse_map_id'), 'warehouse_dock_stations', ['warehouse_map_id'], unique=False)
    op.create_table('warehouse_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_map_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('epsg', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_map_id'], ['warehouse_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_map_id', 'version', name='uq_warehouse_model_version')
    )
    op.create_index('idx_warehouse_model_status', 'warehouse_models', ['status'], unique=False)
    op.create_index(op.f('ix_warehouse_models_warehouse_map_id'), 'warehouse_models', ['warehouse_map_id'], unique=False)
    op.create_table('alert_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['operational_alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_deliveries_alert_id'), 'alert_deliveries', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_deliveries_channel'), 'alert_deliveries', ['channel'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herd_id', sa.Integer(), nullable=False),
    sa.Column('collar_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('species', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_collar_id'), 'animals', ['collar_id'], unique=True)
    op.create_index(op.f('ix_animals_herd_id'), 'animals', ['herd_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['field_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_model_type', 'assets', ['model_id', 'type'], unique=False)
    op.create_index('idx_assets_bbox', 'assets', ['bbox'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_assets_model_id'), 'assets', ['model_id'], unique=False)
    op.create_table('herd_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herd_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herd_tasks_flight_id'), 'herd_tasks', ['flight_id'], unique=False)
    op.create_index(op.f('ix_herd_tasks_herd_id'), 'herd_tasks', ['herd_id'], unique=False)
    op.create_table('mapping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('processor', sa.String(length=32), nullable=False),
    sa.Column('processor_task_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['field_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mapping_job_status', 'mapping_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_mapping_jobs_field_id'), 'mapping_jobs', ['field_id'], unique=False)
    op.create_index(op.f('ix_mapping_jobs_model_id'), 'mapping_jobs', ['model_id'], unique=False)
    op.create_index(op.f('ix_mapping_jobs_processor_task_id'), 'mapping_jobs', ['processor_task_id'], unique=False)
    op.create_table('mission_runtimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_flight_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('preflight_run_id', sa.Integer(), nullable=True),
    sa.Column('mission_name', sa.String(length=255), nullable=False),
    sa.Column('mission_type', sa.String(length=64), nullable=False),
    sa.Column('mission_task_type', sa.String(length=64), nullable=True),
    sa.Column('private_patrol_task_type', sa.String(length=64), nullable=True),
    sa.Column('ai_tasks', sa.JSON(), nullable=False),
    sa.Column('preflight_run_uuid', sa.String(length=128), nullable=True),
    sa.Column('idempotency_results', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('operator_note', sa.Text(), nullable=True),
    sa.Column('resume_metadata', sa.JSON(), nullable=False),
    sa.Column('mission_params', sa.JSON(), nullable=False),
    sa.Column('command_audit', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preflight_run_id'], ['preflight_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mission_runtime_state_created', 'mission_runtimes', ['state', 'created_at'], unique=False)
    op.create_index('idx_mission_runtime_user', 'mission_runtimes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_mission_runtimes_client_flight_id'), 'mission_runtimes', ['client_flight_id'], unique=True)
    op.create_index(op.f('ix_mission_runtimes_flight_id'), 'mission_runtimes', ['flight_id'], unique=False)
    op.create_index(op.f('ix_mission_runtimes_mission_task_type'), 'mission_runtimes', ['mission_task_type'], unique=False)
    op.create_index(op.f('ix_mission_runtimes_mission_type'), 'mission_runtimes', ['mission_type'], unique=False)
    op.create_index(op.f('ix_mission_runtimes_preflight_run_id'), 'mission_runtimes', ['preflight_run_id'], unique=False)
    op.create_index(op.f('ix_mission_runtimes_state'), 'mission_runtimes', ['state'], unique=False)
    op.create_index(op.f('ix_mission_runtimes_user_id'), 'mission_runtimes', ['user_id'], unique=False)
    op.create_table('patrol_detections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('telemetry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('mission_task_type', sa.String(length=64), nullable=False),
    sa.Column('ai_task', sa.String(length=64), nullable=False),
    sa.Column('object_class', sa.String(length=64), nullable=False),
    sa.Column('anomaly_type', sa.String(length=64), nullable=True),
    sa.Column('track_id', sa.String(length=64), nullable=True),
    sa.Column('zone_name', sa.String(length=128), nullable=True),
    sa.Column('checkpoint_index', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_xyxy', sa.JSON(), nullable=False),
    sa.Column('centroid_xy', sa.JSON(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('groundspeed', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('snapshot_path', sa.String(length=1024), nullable=True),
    sa.Column('clip_path', sa.String(length=1024), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['telemetry_id'], ['telemetry.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patrol_det_flight_time', 'patrol_detections', ['flight_id', 'created_at'], unique=False)
    op.create_index('idx_patrol_det_flight_track', 'patrol_detections', ['flight_id', 'track_id'], unique=False)
    op.create_index('idx_patrol_det_object_anomaly', 'patrol_detections', ['object_class', 'anomaly_type'], unique=False)
    op.create_index('idx_patrol_det_task_ai', 'patrol_detections', ['mission_task_type', 'ai_task'], unique=False)
    op.create_index(op.f('ix_patrol_detections_ai_task'), 'patrol_detections', ['ai_task'], unique=False)
    op.create_index(op.f('ix_patrol_detections_anomaly_type'), 'patrol_detections', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_patrol_detections_checkpoint_index'), 'patrol_detections', ['checkpoint_index'], unique=False)
    op.create_index(op.f('ix_patrol_detections_created_at'), 'patrol_detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_patrol_detections_flight_id'), 'patrol_detections', ['flight_id'], unique=False)
    op.create_index(op.f('ix_patrol_detections_frame_id'), 'patrol_detections', ['frame_id'], unique=False)
    op.create_index(op.f('ix_patrol_detections_mission_task_type'), 'patrol_detections', ['mission_task_type'], unique=False)
    op.create_index(op.f('ix_patrol_detections_object_class'), 'patrol_detections', ['object_class'], unique=False)
    op.create_index(op.f('ix_patrol_detections_telemetry_id'), 'patrol_detections', ['telemetry_id'], unique=False)
    op.create_index(op.f('ix_patrol_detections_track_id'), 'patrol_detections', ['track_id'], unique=False)
    op.create_index(op.f('ix_patrol_detections_zone_name'), 'patrol_detections', ['zone_name'], unique=False)
    op.create_table('patrol_incidents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('mission_task_type', sa.String(length=64), nullable=False),
    sa.Column('incident_type', sa.String(length=64), nullable=False),
    sa.Column('primary_object_class', sa.String(length=64), nullable=True),
    sa.Column('primary_track_id', sa.String(length=64), nullable=True),
    sa.Column('ai_task', sa.String(length=64), nullable=True),
    sa.Column('zone_name', sa.String(length=128), nullable=True),
    sa.Column('checkpoint_index', sa.Integer(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lon', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lon', sa.Float(), nullable=True),
    sa.Column('peak_confidence', sa.Float(), nullable=True),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('first_detection_id', sa.BigInteger(), nullable=True),
    sa.Column('last_detection_id', sa.BigInteger(), nullable=True),
    sa.Column('snapshot_path', sa.String(length=1024), nullable=True),
    sa.Column('clip_path', sa.String(length=1024), nullable=True),
    sa.Column('last_alert_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_alert_id'], ['operational_alerts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patrol_inc_flight_opened', 'patrol_incidents', ['flight_id', 'opened_at'], unique=False)
    op.create_index('idx_patrol_inc_track_status', 'patrol_incidents', ['primary_track_id', 'status'], unique=False)
    op.create_index('idx_patrol_inc_type_status', 'patrol_incidents', ['incident_type', 'status'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_ai_task'), 'patrol_incidents', ['ai_task'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_checkpoint_index'), 'patrol_incidents', ['checkpoint_index'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_first_detection_id'), 'patrol_incidents', ['first_detection_id'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_flight_id'), 'patrol_incidents', ['flight_id'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_incident_type'), 'patrol_incidents', ['incident_type'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_last_alert_id'), 'patrol_incidents', ['last_alert_id'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_last_detection_id'), 'patrol_incidents', ['last_detection_id'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_mission_task_type'), 'patrol_incidents', ['mission_task_type'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_opened_at'), 'patrol_incidents', ['opened_at'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_primary_object_class'), 'patrol_incidents', ['primary_object_class'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_primary_track_id'), 'patrol_incidents', ['primary_track_id'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_status'), 'patrol_incidents', ['status'], unique=False)
    op.create_index(op.f('ix_patrol_incidents_zone_name'), 'patrol_incidents', ['zone_name'], unique=False)
    op.create_table('warehouse_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['warehouse_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_warehouse_asset_model_type', 'warehouse_assets', ['model_id', 'type'], unique=False)
    op.create_index('idx_warehouse_assets_bbox', 'warehouse_assets', ['bbox'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_warehouse_assets_model_id'), 'warehouse_assets', ['model_id'], unique=False)
    op.create_table('warehouse_mapping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_map_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('processor', sa.String(length=32), nullable=False),
    sa.Column('processor_task_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['warehouse_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_map_id'], ['warehouse_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_warehouse_mapping_job_status', 'warehouse_mapping_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_warehouse_mapping_jobs_model_id'), 'warehouse_mapping_jobs', ['model_id'], unique=False)
    op.create_index(op.f('ix_warehouse_mapping_jobs_processor_task_id'), 'warehouse_mapping_jobs', ['processor_task_id'], unique=False)
    op.create_index(op.f('ix_warehouse_mapping_jobs_warehouse_map_id'), 'warehouse_mapping_jobs', ['warehouse_map_id'], unique=False)
    op.create_table('animal_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('activity', sa.Float(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_animal_pos_animal_time', 'animal_positions', ['animal_id', 'created_at'], unique=False)
    op.create_index('idx_animal_positions_point', 'animal_positions', ['point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_animal_positions_animal_id'), 'animal_positions', ['animal_id'], unique=False)
    op.create_table('operator_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(length=64), nullable=False),
    sa.Column('mission_runtime_id', sa.Integer(), nullable=True),
    sa.Column('client_flight_id', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('state_before', sa.String(length=32), nullable=False),
    sa.Column('state_after', sa.String(length=32), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_runtime_id'], ['mission_runtimes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_operator_command_flight', 'operator_commands', ['client_flight_id', 'requested_at'], unique=False)
    op.create_index('idx_operator_command_runtime', 'operator_commands', ['mission_runtime_id', 'requested_at'], unique=False)
    op.create_index(op.f('ix_operator_commands_client_flight_id'), 'operator_commands', ['client_flight_id'], unique=False)
    op.create_index(op.f('ix_operator_commands_command'), 'operator_commands', ['command'], unique=False)
    op.create_index(op.f('ix_operator_commands_command_id'), 'operator_commands', ['command_id'], unique=True)
    op.create_index(op.f('ix_operator_commands_mission_runtime_id'), 'operator_commands', ['mission_runtime_id'], unique=False)
    op.create_table('patrol_incident_detections',
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('detection_id', sa.BigInteger(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['patrol_detections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['patrol_incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'detection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patrol_incident_detections')
    op.drop_index(op.f('ix_operator_commands_mission_runtime_id'), table_name='operator_commands')
    op.drop_index(op.f('ix_operator_commands_command_id'), table_name='operator_commands')
    op.drop_index(op.f('ix_operator_commands_command'), table_name='operator_commands')
    op.drop_index(op.f('ix_operator_commands_client_flight_id'), table_name='operator_commands')
    op.drop_index('idx_operator_command_runtime', table_name='operator_commands')
    op.drop_index('idx_operator_command_flight', table_name='operator_commands')
    op.drop_table('operator_commands')
    op.drop_index(op.f('ix_animal_positions_animal_id'), table_name='animal_positions')
    op.drop_index('idx_animal_positions_point', table_name='animal_positions', postgresql_using='gist')
    op.drop_index('idx_animal_pos_animal_time', table_name='animal_positions')
    op.drop_table('animal_positions')
    op.drop_index(op.f('ix_warehouse_mapping_jobs_warehouse_map_id'), table_name='warehouse_mapping_jobs')
    op.drop_index(op.f('ix_warehouse_mapping_jobs_processor_task_id'), table_name='warehouse_mapping_jobs')
    op.drop_index(op.f('ix_warehouse_mapping_jobs_model_id'), table_name='warehouse_mapping_jobs')
    op.drop_index('idx_warehouse_mapping_job_status', table_name='warehouse_mapping_jobs')
    op.drop_table('warehouse_mapping_jobs')
    op.drop_index(op.f('ix_warehouse_assets_model_id'), table_name='warehouse_assets')
    op.drop_index('idx_warehouse_assets_bbox', table_name='warehouse_assets', postgresql_using='gist')
    op.drop_index('idx_warehouse_asset_model_type', table_name='warehouse_assets')
    op.drop_table('warehouse_assets')
    op.drop_index(op.f('ix_patrol_incidents_zone_name'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_status'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_primary_track_id'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_primary_object_class'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_opened_at'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_mission_task_type'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_last_detection_id'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_last_alert_id'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_incident_type'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_flight_id'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_first_detection_id'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_checkpoint_index'), table_name='patrol_incidents')
    op.drop_index(op.f('ix_patrol_incidents_ai_task'), table_name='patrol_incidents')
    op.drop_index('idx_patrol_inc_type_status', table_name='patrol_incidents')
    op.drop_index('idx_patrol_inc_track_status', table_name='patrol_incidents')
    op.drop_index('idx_patrol_inc_flight_opened', table_name='patrol_incidents')
    op.drop_table('patrol_incidents')
    op.drop_index(op.f('ix_patrol_detections_zone_name'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_track_id'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_telemetry_id'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_object_class'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_mission_task_type'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_frame_id'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_flight_id'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_created_at'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_checkpoint_index'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_anomaly_type'), table_name='patrol_detections')
    op.drop_index(op.f('ix_patrol_detections_ai_task'), table_name='patrol_detections')
    op.drop_index('idx_patrol_det_task_ai', table_name='patrol_detections')
    op.drop_index('idx_patrol_det_object_anomaly', table_name='patrol_detections')
    op.drop_index('idx_patrol_det_flight_track', table_name='patrol_detections')
    op.drop_index('idx_patrol_det_flight_time', table_name='patrol_detections')
    op.drop_table('patrol_detections')
    op.drop_index(op.f('ix_mission_runtimes_user_id'), table_name='mission_runtimes')
    op.drop_index(op.f('ix_mission_runtimes_state'), table_name='mission_runtimes')
    op.drop_index(op.f('ix_mission_runtimes_preflight_run_id'), table_name='mission_runtimes')
    op.drop_index(op.f('ix_mission_runtimes_mission_type'), table_name='mission_runtimes')
    op.drop_index(op.f('ix_mission_runtimes_mission_task_type'), table_name='mission_runtimes')
    op.drop_index(op.f('ix_mission_runtimes_flight_id'), table_name='mission_runtimes')
    op.drop_index(op.f('ix_mission_runtimes_client_flight_id'), table_name='mission_runtimes')
    op.drop_index('idx_mission_runtime_user', table_name='mission_runtimes')
    op.drop_index('idx_mission_runtime_state_created', table_name='mission_runtimes')
    op.drop_table('mission_runtimes')
    op.drop_index(op.f('ix_mapping_jobs_processor_task_id'), table_name='mapping_jobs')
    op.drop_index(op.f('ix_mapping_jobs_model_id'), table_name='mapping_jobs')
    op.drop_index(op.f('ix_mapping_jobs_field_id'), table_name='mapping_jobs')
    op.drop_index('idx_mapping_job_status', table_name='mapping_jobs')
    op.drop_table('mapping_jobs')
    op.drop_index(op.f('ix_herd_tasks_herd_id'), table_name='herd_tasks')
    op.drop_index(op.f('ix_herd_tasks_flight_id'), table_name='herd_tasks')
    op.drop_table('herd_tasks')
    op.drop_index(op.f('ix_assets_model_id'), table_name='assets')
    op.drop_index('idx_assets_bbox', table_name='assets', postgresql_using='gist')
    op.drop_index('idx_asset_model_type', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_animals_herd_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_collar_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_alert_deliveries_channel'), table_name='alert_deliveries')
    op.drop_index(op.f('ix_alert_deliveries_alert_id'), table_name='alert_deliveries')
    op.drop_table('alert_deliveries')
    op.drop_index(op.f('ix_warehouse_models_warehouse_map_id'), table_name='warehouse_models')
    op.drop_index('idx_warehouse_model_status', table_name='warehouse_models')
    op.drop_table('warehouse_models')
    op.drop_index(op.f('ix_warehouse_dock_stations_warehouse_map_id'), table_name='warehouse_dock_stations')
    op.drop_index(op.f('ix_warehouse_dock_stations_marker_id'), table_name='warehouse_dock_stations')
    op.drop_table('warehouse_dock_stations')
    op.drop_index(op.f('ix_telemetry_frame_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_flight_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_preflight_runs_user_id'), table_name='preflight_runs')
    op.drop_index(op.f('ix_preflight_runs_run_uuid'), table_name='preflight_runs')
    op.drop_index(op.f('ix_preflight_runs_overall_status'), table_name='preflight_runs')
    op.drop_index(op.f('ix_preflight_runs_mission_type'), table_name='preflight_runs')
    op.drop_index(op.f('ix_preflight_runs_flight_id'), table_name='preflight_runs')
    op.drop_index('idx_preflight_run_status_created', table_name='preflight_runs')
    op.drop_index('idx_preflight_run_flight', table_name='preflight_runs')
    op.drop_table('preflight_runs')
    op.drop_index(op.f('ix_operational_alerts_status'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_rule_type'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_dedupe_key'), table_name='operational_alerts')
    op.drop_index(op.f('ix_operational_alerts_acknowledged_by_user_id'), table_name='operational_alerts')
    op.drop_index('idx_operational_alert_status_triggered', table_name='operational_alerts')
    op.drop_index('idx_operational_alert_rule_status', table_name='operational_alerts')
    op.drop_table('operational_alerts')
    op.drop_index(op.f('ix_obstacles_field_id'), table_name='obstacles')
    op.drop_index('idx_obstacles_location', table_name='obstacles', postgresql_using='gist')
    op.drop_table('obstacles')
    op.drop_index(op.f('ix_herds_pasture_geofence_id'), table_name='herds')
    op.drop_index(op.f('ix_herds_name'), table_name='herds')
    op.drop_table('herds')
    op.drop_index(op.f('ix_flight_events_flight_id'), table_name='flight_events')
    op.drop_table('flight_events')
    op.drop_index(op.f('ix_field_models_field_id'), table_name='field_models')
    op.drop_index('idx_field_model_status', table_name='field_models')
    op.drop_table('field_models')
    op.drop_index(op.f('ix_warehouse_maps_owner_id'), table_name='warehouse_maps')
    op.drop_index(op.f('ix_warehouse_maps_name'), table_name='warehouse_maps')
    op.drop_index('idx_warehouse_maps_centroid', table_name='warehouse_maps', postgresql_using='gist')
    op.drop_index('idx_warehouse_maps_boundary', table_name='warehouse_maps', postgresql_using='gist')
    op.drop_table('warehouse_maps')
    op.drop_index(op.f('ix_vault_secrets_name'), table_name='vault_secrets')
    op.drop_table('vault_secrets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_mavlink_event_flight_id'), table_name='mavlink_event')
    op.drop_index('idx_evt_flt_time', table_name='mavlink_event')
    op.drop_table('mavlink_event')
    op.drop_index(op.f('ix_geofences_name'), table_name='geofences')
    op.drop_index('idx_geofences_polygon', table_name='geofences', postgresql_using='gist')
    op.drop_table('geofences')
    op.drop_table('flights')
    op.drop_index(op.f('ix_fields_owner_id'), table_name='fields')
    op.drop_index(op.f('ix_fields_name'), table_name='fields')
    op.drop_index('idx_fields_centroid', table_name='fields', postgresql_using='gist')
    op.drop_index('idx_fields_boundary', table_name='fields', postgresql_using='gist')
    op.drop_table('fields')
    # ### end Alembic commands ###
