"""generate tables

Revision ID: 3f2391ebb64e
Revises: 
Create Date: 2026-03-01 20:52:04.471240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3f2391ebb64e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fields_boundary', 'fields', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index('idx_fields_centroid', 'fields', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_fields_name'), 'fields', ['name'], unique=False)
    op.create_index(op.f('ix_fields_owner_id'), 'fields', ['owner_id'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lon', sa.Float(), nullable=False),
    sa.Column('start_alt', sa.Float(), nullable=False),
    sa.Column('dest_lat', sa.Float(), nullable=False),
    sa.Column('dest_lon', sa.Float(), nullable=False),
    sa.Column('dest_alt', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('min_alt_m', sa.Float(), nullable=True),
    sa.Column('max_alt_m', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geofences_polygon', 'geofences', ['polygon'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_geofences_name'), 'geofences', ['name'], unique=False)
    op.create_table('mavlink_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('msg_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('time_boot_ms', sa.BigInteger(), nullable=True),
    sa.Column('time_unix_usec', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'msg_type', 'time_boot_ms', name='uq_evt_flt_type_frame')
    )
    op.create_index('idx_evt_flt_time', 'mavlink_event', ['flight_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_mavlink_event_flight_id'), 'mavlink_event', ['flight_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vault_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_vault_secret_name')
    )
    op.create_index(op.f('ix_vault_secrets_name'), 'vault_secrets', ['name'], unique=True)
    op.create_table('field_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('gsd_cm', sa.Float(), nullable=True),
    sa.Column('epsg', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'version', name='uq_field_model_version')
    )
    op.create_index('idx_field_model_status', 'field_models', ['status'], unique=False)
    op.create_index(op.f('ix_field_models_field_id'), 'field_models', ['field_id'], unique=False)
    op.create_table('flight_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_events_flight_id'), 'flight_events', ['flight_id'], unique=False)
    op.create_table('herds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('pasture_geofence_id', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pasture_geofence_id'], ['geofences.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herds_name'), 'herds', ['name'], unique=False)
    op.create_index(op.f('ix_herds_pasture_geofence_id'), 'herds', ['pasture_geofence_id'], unique=False)
    op.create_table('obstacles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_obstacles_location', 'obstacles', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_obstacles_field_id'), 'obstacles', ['field_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('alt', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=False),
    sa.Column('groundspeed', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=True),
    sa.Column('battery_current', sa.Float(), nullable=True),
    sa.Column('battery_remaining', sa.Float(), nullable=True),
    sa.Column('system_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_id', 'frame_id', name='uq_telemetry_flight_frame_id')
    )
    op.create_index(op.f('ix_telemetry_flight_id'), 'telemetry', ['flight_id'], unique=False)
    op.create_index(op.f('ix_telemetry_frame_id'), 'telemetry', ['frame_id'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herd_id', sa.Integer(), nullable=False),
    sa.Column('collar_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('species', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_collar_id'), 'animals', ['collar_id'], unique=True)
    op.create_index(op.f('ix_animals_herd_id'), 'animals', ['herd_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['field_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_asset_model_type', 'assets', ['model_id', 'type'], unique=False)
    op.create_index('idx_assets_bbox', 'assets', ['bbox'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_assets_model_id'), 'assets', ['model_id'], unique=False)
    op.create_table('herd_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herd_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('flight_id', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['herd_id'], ['herds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_herd_tasks_flight_id'), 'herd_tasks', ['flight_id'], unique=False)
    op.create_index(op.f('ix_herd_tasks_herd_id'), 'herd_tasks', ['herd_id'], unique=False)
    op.create_table('mapping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('processor', sa.String(length=32), nullable=False),
    sa.Column('processor_task_id', sa.String(length=64), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['field_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mapping_job_status', 'mapping_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_mapping_jobs_field_id'), 'mapping_jobs', ['field_id'], unique=False)
    op.create_index(op.f('ix_mapping_jobs_model_id'), 'mapping_jobs', ['model_id'], unique=False)
    op.create_index(op.f('ix_mapping_jobs_processor_task_id'), 'mapping_jobs', ['processor_task_id'], unique=False)
    op.create_table('animal_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('activity', sa.Float(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_animal_pos_animal_time', 'animal_positions', ['animal_id', 'created_at'], unique=False)
    op.create_index('idx_animal_positions_point', 'animal_positions', ['point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_animal_positions_animal_id'), 'animal_positions', ['animal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animal_positions_animal_id'), table_name='animal_positions')
    op.drop_index('idx_animal_positions_point', table_name='animal_positions', postgresql_using='gist')
    op.drop_index('idx_animal_pos_animal_time', table_name='animal_positions')
    op.drop_table('animal_positions')
    op.drop_index(op.f('ix_mapping_jobs_processor_task_id'), table_name='mapping_jobs')
    op.drop_index(op.f('ix_mapping_jobs_model_id'), table_name='mapping_jobs')
    op.drop_index(op.f('ix_mapping_jobs_field_id'), table_name='mapping_jobs')
    op.drop_index('idx_mapping_job_status', table_name='mapping_jobs')
    op.drop_table('mapping_jobs')
    op.drop_index(op.f('ix_herd_tasks_herd_id'), table_name='herd_tasks')
    op.drop_index(op.f('ix_herd_tasks_flight_id'), table_name='herd_tasks')
    op.drop_table('herd_tasks')
    op.drop_index(op.f('ix_assets_model_id'), table_name='assets')
    op.drop_index('idx_assets_bbox', table_name='assets', postgresql_using='gist')
    op.drop_index('idx_asset_model_type', table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_animals_herd_id'), table_name='animals')
    op.drop_index(op.f('ix_animals_collar_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_telemetry_frame_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_flight_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_obstacles_field_id'), table_name='obstacles')
    op.drop_index('idx_obstacles_location', table_name='obstacles', postgresql_using='gist')
    op.drop_table('obstacles')
    op.drop_index(op.f('ix_herds_pasture_geofence_id'), table_name='herds')
    op.drop_index(op.f('ix_herds_name'), table_name='herds')
    op.drop_table('herds')
    op.drop_index(op.f('ix_flight_events_flight_id'), table_name='flight_events')
    op.drop_table('flight_events')
    op.drop_index(op.f('ix_field_models_field_id'), table_name='field_models')
    op.drop_index('idx_field_model_status', table_name='field_models')
    op.drop_table('field_models')
    op.drop_index(op.f('ix_vault_secrets_name'), table_name='vault_secrets')
    op.drop_table('vault_secrets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_mavlink_event_flight_id'), table_name='mavlink_event')
    op.drop_index('idx_evt_flt_time', table_name='mavlink_event')
    op.drop_table('mavlink_event')
    op.drop_index(op.f('ix_geofences_name'), table_name='geofences')
    op.drop_index('idx_geofences_polygon', table_name='geofences', postgresql_using='gist')
    op.drop_table('geofences')
    op.drop_table('flights')
    op.drop_index(op.f('ix_fields_owner_id'), table_name='fields')
    op.drop_index(op.f('ix_fields_name'), table_name='fields')
    op.drop_index('idx_fields_centroid', table_name='fields', postgresql_using='gist')
    op.drop_index('idx_fields_boundary', table_name='fields', postgresql_using='gist')
    op.drop_table('fields')
    # ### end Alembic commands ###
