"""generate tables

Revision ID: 57052cb0a8ff
Revises: 8c4c9d6ef5a1
Create Date: 2026-03-18 02:03:24.789647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '57052cb0a8ff'
down_revision: Union[str, Sequence[str], None] = '8c4c9d6ef5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
