#!/usr/bin/env bash
set -Eeuo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-42}"
export ROS_DISTRO="${ROS_DISTRO:-jazzy}"
export ROS_WS_SETUP="${ROS_WS_SETUP:-warehouse_ros2_ws/install/setup.bash}"

export WAREHOUSE_GAZEBO_SIM="${WAREHOUSE_GAZEBO_SIM:-1}"
export WAREHOUSE_USE_SIM_TIME="${WAREHOUSE_USE_SIM_TIME:-1}"
export WAREHOUSE_TOPIC_PROFILE="${WAREHOUSE_TOPIC_PROFILE:-gazebo}"
export WAREHOUSE_ROS_PROFILE="${WAREHOUSE_ROS_PROFILE:-gazebo}"

export WAREHOUSE_ROS_BRIDGE_URL="${WAREHOUSE_ROS_BRIDGE_URL:-http://127.0.0.1:8088}"
export WAREHOUSE_ROS_WS_URL="${WAREHOUSE_ROS_WS_URL:-ws://127.0.0.1:9090}"

export WAREHOUSE_HEALTH_BACKGROUND_PROBE="${WAREHOUSE_HEALTH_BACKGROUND_PROBE:-1}"
export WAREHOUSE_HEALTH_REFRESH_INTERVAL_S="${WAREHOUSE_HEALTH_REFRESH_INTERVAL_S:-3}"
export WAREHOUSE_HEALTH_DEEP_STALE_S="${WAREHOUSE_HEALTH_DEEP_STALE_S:-10}"
export WAREHOUSE_HEALTH_STARTUP_DELAY_S="${WAREHOUSE_HEALTH_STARTUP_DELAY_S:-1.0}"
export WAREHOUSE_TOPIC_HEALTH_MODE="${WAREHOUSE_TOPIC_HEALTH_MODE:-presence}"
export WAREHOUSE_GAZEBO_PROBE_ON_HEALTH="${WAREHOUSE_GAZEBO_PROBE_ON_HEALTH:-1}"
export WAREHOUSE_TF_PROBE_ON_HEALTH="${WAREHOUSE_TF_PROBE_ON_HEALTH:-1}"

export WAREHOUSE_ROS_TOPIC_LIST_BG_TIMEOUT_S="${WAREHOUSE_ROS_TOPIC_LIST_BG_TIMEOUT_S:-3.5}"
export WAREHOUSE_ROS_TOPIC_LIST_BG_ATTEMPTS="${WAREHOUSE_ROS_TOPIC_LIST_BG_ATTEMPTS:-2}"
export WAREHOUSE_ROS_TOPIC_LIST_TIMEOUT_S="${WAREHOUSE_ROS_TOPIC_LIST_TIMEOUT_S:-1.0}"
export WAREHOUSE_ROS_TOPIC_LIST_ATTEMPTS="${WAREHOUSE_ROS_TOPIC_LIST_ATTEMPTS:-1}"

# ros2 topic info/hz on a live Gazebo graph often needs several seconds (many endpoints).
export WAREHOUSE_TOPIC_INFO_TIMEOUT_S="${WAREHOUSE_TOPIC_INFO_TIMEOUT_S:-8.0}"
export WAREHOUSE_TOPIC_HZ_TIMEOUT_S="${WAREHOUSE_TOPIC_HZ_TIMEOUT_S:-5.0}"
export WAREHOUSE_TOPIC_HZ_WINDOW="${WAREHOUSE_TOPIC_HZ_WINDOW:-2}"
export WAREHOUSE_TOPIC_PROBE_WORKERS="${WAREHOUSE_TOPIC_PROBE_WORKERS:-4}"
export WAREHOUSE_TOPIC_ECHO_PROBE="${WAREHOUSE_TOPIC_ECHO_PROBE:-0}"
export WAREHOUSE_TOPIC_RESOLVE_WITH_PROBES="${WAREHOUSE_TOPIC_RESOLVE_WITH_PROBES:-0}"
export WAREHOUSE_TOPIC_REQUIRE_HZ="${WAREHOUSE_TOPIC_REQUIRE_HZ:-0}"

export WAREHOUSE_RECORD_SNAPSHOT_ON_STOP="${WAREHOUSE_RECORD_SNAPSHOT_ON_STOP:-0}"
export WAREHOUSE_RECORD_SNAPSHOT_DURATION_S="${WAREHOUSE_RECORD_SNAPSHOT_DURATION_S:-2}"

export WAREHOUSE_CAPTURE_ROOT="${WAREHOUSE_CAPTURE_ROOT:-${PWD}/backend/storage/warehouse_ros}"
export WAREHOUSE_ROS_CAPTURE_ROOT="${WAREHOUSE_ROS_CAPTURE_ROOT:-${WAREHOUSE_CAPTURE_ROOT}}"
mkdir -p "${WAREHOUSE_CAPTURE_ROOT}"

export AMENT_TRACE_SETUP_FILES="${AMENT_TRACE_SETUP_FILES:-}"

set +u
source "/opt/ros/${ROS_DISTRO}/setup.bash"

if [ -f "${ROS_WS_SETUP}" ]; then
  source "${ROS_WS_SETUP}"
else
  echo "[warehouse_bridge] WARNING: ROS_WS_SETUP not found: ${ROS_WS_SETUP}" >&2
fi
set -u

export PYTHONPATH="${PWD}/warehouse_ros2_ws/src/warehouse_mapping_bridge:${PYTHONPATH:-}"

BRIDGE_PYTHON="${WAREHOUSE_BRIDGE_PYTHON:-${PWD}/.venv/bin/python}"
if [ ! -x "${BRIDGE_PYTHON}" ]; then
  BRIDGE_PYTHON="$(command -v python3)"
fi

echo "[warehouse_bridge] start app_python=$("${BRIDGE_PYTHON}" -V 2>&1) python_path=${BRIDGE_PYTHON}"
echo "[warehouse_bridge] profile=${WAREHOUSE_TOPIC_PROFILE} capture_root=${WAREHOUSE_CAPTURE_ROOT}"
echo "[warehouse_bridge] bridge=${WAREHOUSE_ROS_BRIDGE_URL} ws=${WAREHOUSE_ROS_WS_URL} ROS_DOMAIN_ID=${ROS_DOMAIN_ID}"

# Do not block HTTP service startup on ROS topics.
# The bridge service /health endpoint must be available even when topics are missing,
# so the backend/UI can show a degraded preflight report instead of 503 unreachable.
if [ "${WAREHOUSE_BRIDGE_WAIT_FOR_TOPICS:-1}" = "1" ]; then
  echo "[warehouse_bridge] topic wait is delegated to /health deep checks; starting HTTP bridge now"
fi

exec "${BRIDGE_PYTHON}" -m warehouse_mapping_bridge.bridge_service