"""Tenant-authorized access to locally stored irrigation assets."""

from __future__ import annotations

from pathlib import Path

from sqlalchemy.ext.asyncio import AsyncSession

from backend.core.config.runtime import settings
from backend.modules.identity.models import User
from backend.modules.irrigation.service.processing import IrrigationProcessingService

_ASSET_DIRECTORIES = frozenset({"captures", "outputs"})


def _configured_extensions() -> frozenset[str]:
    return frozenset(
        item.strip().lower()
        for item in settings.irrigation_allowed_image_extensions.split(",")
        if item.strip()
    )


def _asset_parts(asset_path: str) -> tuple[str, ...] | None:
    """Return validated URL path parts for generated irrigation image assets."""
    if (
        not asset_path
        or asset_path.startswith(("/", "\\"))
        or asset_path.endswith(("/", "\\"))
        or "\x00" in asset_path
        or "//" in asset_path
    ):
        return None

    # Storage layout is generated by IrrigationProcessingService:
    # ``<mission-id>/{captures|outputs}/<image>``.  Do not expose arbitrary
    # files placed deeper in a mission directory (sidecars, logs, etc.).
    parts = tuple(asset_path.split("/"))
    if len(parts) != 3:
        return None
    if any(part in {"", ".", ".."} or "\\" in part for part in parts):
        return None
    if parts[1] not in _ASSET_DIRECTORIES:
        return None

    extension = Path(parts[-1]).suffix.lower()
    if extension not in _configured_extensions():
        return None
    return parts


async def resolve_owned_asset(
    db: AsyncSession,
    *,
    asset_path: str,
    user: User,
) -> Path | None:
    parts = _asset_parts(asset_path)
    if parts is None:
        return None

    service = IrrigationProcessingService()
    mission_id = parts[0]
    mission = await service.get_owned_mission(db, mission_id=mission_id, user=user)
    if mission is None:
        return None

    root = Path(settings.irrigation_storage_dir).resolve()
    candidate = root.joinpath(*parts)
    try:
        resolved = candidate.resolve(strict=True)
        resolved.relative_to(root)
    except (OSError, RuntimeError, ValueError):
        return None
    if not resolved.is_file():
        return None
    return resolved
